### ISSUE TITLE
External URL Linking

### ISSUE THREAD

**Issue by lachlangeppVentia** [ngrondin/redback#6]
As a developer I want to be able to route my clients out to other applications using an external link via a button. It would allow me to construct the URL in such a fashion that parameters could be added to enrich the URL that enable authentication or direct me to specific pages into the other webapp.

**Comment by ngrondin** [comment]
You can now do this using Buttons or ActionGroups.

The configu is as follows:
												{
													"action":"externallink",
													"param":"'https://url/' + object.data.attribute",
													"label":"Link Label"
												}

paramis the link and is a javascript expression evaluated against the context of the selected object.
